### ISSUE TITLE
Incorrect Import statement in Glyph Documentation

### ISSUE THREAD

**Issue by BrownRiceRice** [dart-lang/angular2_components#10]
The class docs for the Glyph component say to include the following link at the top of the page.
```
<link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/icon?family=Material+Icons+Extended">
```

However, none of the icons show up using this link.  The [example code](https://github.com/dart-lang/angular2_components_example) uses this link instead:
```
<link rel="stylesheet" type="text/css" 
    href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
which works properly. 

I think this is because the Glyph component adds the `.material-icons` class to a tag, but that class is called `.material-icons-extended` in the extended stylesheet.  

The docs should be changed to reflect this, and I guess the extended set of icons should be supported eventually.

**Comment by nshahan** [comment]
Thanks for letting us know. Fixed in a16b3ddbe260ed9ea0d3bb3103d890a4e9b5cdc5.
