### ISSUE TITLE
TODO when Angular2 supports conditionally adding/removing attributes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2_components#13]
https://github.com/dart-lang/angular2_components/blob/master/lib/src/components/material_button/material_button.dart#L13

angular/angular#2869 is fixed

A value of `null` causes the attribute to be removed.

**Comment by matanlurey** [comment]
Thanks!

**Comment by nshahan** [comment]
Update is currently in progress internally.

**Comment by nshahan** [comment]
Cleanup landed in #57.
