### ISSUE TITLE
Glyph touch button  

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular2_components#15]
Is the a way to implement de touch glyph button inside an input.
For example a glyph button to show the password content.

**Comment by zoechi** [comment]
Can't imagine how that should look like. Can you elaborate a bit more or add a screenshot from another implementation?

**Comment by arcas0803** [comment]
This is an example.
[http://wsnippets.com/wp-content/uploads/2013/11/show-hide-password1.png]

**Comment by zoechi** [comment]
Looks like the example in https://dart-lang.github.io/angular2_components_example/ "With trailing glyph"

**Comment by arcas0803** [comment]
It's not touchable

**Comment by nshahan** [comment]
Just to be clear, are you talking about turning the glyph into a button that does something different than clicking anywhere else in the input box?

**Comment by zoechi** [comment]
I tried to put that icon into a button to open a dropdown. 
I can figure out from the event of the glyph was clicked or something else, but it's ugly.

**Comment by TedSander** [comment]
You can use the ng-content provided in the input for this. Something like this:
<material-input><material-button (trigger)="clicked($event)" trailing></material-button></material-input>

This is just to show how one might do it. I probably wouldn't use material-button for this.

**Comment by zoechi** [comment]
Sounds great. Will try.
