### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular2_components#16]
Glyph component doesn't show the icon, just the title of it.

**Comment by zoechi** [comment]
Works for me. How does your code look like?

You might miss the `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">` in `<head>`

**Comment by nshahan** [comment]
Yes, we are updating the documentation. Take a look at the [example](https://github.com/dart-lang/angular2_components_example/blob/master/web/index.html#L14) web app to see a working version. That should help to get it working for you.

**Comment by arcas0803** [comment]
you're right i miss the stylesheet in the head.
