### ISSUE TITLE
feature request - drag and drop support

### ISSUE THREAD

**Issue by joeblew99** [dart-lang/angular2_components#17]
me and few others use this to do drag and drop with Dart apps.
https://github.com/marcojakob/dart-dnd

But we are wondering if you already support it, or are planning to support Drag and Drop in this library anyway ?
https://github.com/marcojakob/dart-dnd/issues/16

It will help us to know the best roadmap for the library.

**Comment by TedSander** [comment]
We don't have any plans to have general drag and drop capabilities provided by this library at this time. Some components will have drag and drop support, but nothing generic.
