### ISSUE TITLE
glyph icons don't work with ViewEncapsulation.Native

### ISSUE THREAD

**Issue by madisona** [dart-lang/angular2_components#23]
When ViewEncapsulation.Native is used the fonts don't render. You have to include the glyph icons import / css on every component where you want to use the icon.

Can the components be constructed so they always work correctly regardless of the encapsulation method used?

Note: I'm using Polymer for the main layout components and trying to use angular2_components for everything else where possible.

**Comment by matanlurey** [comment]
Hi. We currently don't have any formal support for mixing Polymer with these components.

Perhaps once we hit 1.0.0 we can consider strategies, but for now this is wontfix.
