### ISSUE TITLE
material-input inputText binding not working

### ISSUE THREAD

**Issue by dngsdk** [dart-lang/angular2_components#24]
Hello,

I can't get the example from https://www.dartdocs.org/documentation/angular2_components/0.1.1/angular2_components/MaterialInputComponent-class.html to work: 

<material-input [(inputText)]="text"></material-input>

Basically, there is no way how to set the value of the input. Am I missing something obvious?

Thanks

**Comment by zoechi** [comment]
I guess you are missing the `materialInputDirectives` in `providers: [materialInputDirectives]`

**Comment by kulshekhar** [comment]
The following snippet works for me:

```dart
@Component(
    selector: 'my-component',
    template: '''
    <material-input label="Your Name"></material-input>
    <material-input multiline label="Enter multiple lines here">
    </material-input>
    <material-input [(inputText)]="text"></material-input>
  ''',
    directives: const [materialDirectives])
class MyComponent {
  String text;
}
```

**Comment by dngsdk** [comment]
I'm declaring MaterialInputComponent manually in the list of directives, so this might be the problem. I will check it out later today.

**Comment by kulshekhar** [comment]
`materialInputDirectives` works too

**Comment by TedSander** [comment]
Note you should be using ngModel and the other form directives to set this value. I'm removing [(inputText)]

**Comment by TedSander** [comment]
Best to use the directives list. This will provide the component, the default accessor,  and ngModel. The forms system is designed to use all three of these in concert.
