### ISSUE TITLE
MaterialInputComponent with required attribute invalid even though untouched

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/angular2_components#26]
When adding a material-input to a form with the required attribute set, it will be marked as invalid immediately as soon as the page loads, is there any way to test/mark the invalid state of the component only after the user has interacted with it?

**Comment by TedSander** [comment]
Thanks for reporting this. We have a fix already, and will be available in the next sync.

**Comment by nshahan** [comment]
Ted's fix was released in the updates roll up for version 0.2.0.
