### ISSUE TITLE
Material Toolbar Component

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/angular2_components#33]
I actually built one last night out of necessity (using these components in a project), and once I get home, I'll upload it to Github and share the link here.

Feel free to include it in this package. It's more or less a port of the Polymer [paper-toolbar](https://elements.polymer-project.org/elements/paper-toolbar?view=demo:demo/index.html&active=paper-toolbar).

**Comment by nshahan** [comment]
Thanks! I am excited to see new components get added but we are not currently setup to accept pull requests on this repo at the moment.

**Comment by thosakwe** [comment]
Okay. Then for now, I will publish it separately on Pub.

**Comment by thosakwe** [comment]
Package is available [here](https://pub.dartlang.org/packages/material_toolbar).
