### ISSUE TITLE
Open Max Height Dialog - max-height style does not work correctly in IE 11

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/angular2_components#35]
In IE Version 11.0.9600.18524

If I do the following:
https://dart-lang.github.io/angular2_components_example/
Open the "Modal Dialogs" "Basic no-frills dialogs" "Open Max Height" and then keep clicking "Add Some Text", eventually the footer moves below the display pane.

**Comment by nshahan** [comment]
Thanks for the report. I will investigate.

**Comment by nshahan** [comment]
Thanks for the info. I can confirm I am seeing the same thing. We currently are support the most recent two versions of Chrome, Edge, Firefox, and Safari. Many of the components do work in IE currently but it is not guaranteed.
