### ISSUE TITLE
[Q] Make intl package optional

### ISSUE THREAD

**Issue by John0x** [dart-lang/angular2_components#36]
Hello, would it be possible to make the intl package optional or decrease its size?
It takes around 400kb and as far as I have seen it is only used to get localization for default texts and messages.
I guess there is no way to use tree-shaking to reduce the size?

**Comment by daniel-v** [comment]
I'm also curious if we can get around the extra weight.

**Comment by TedSander** [comment]
We don't have any plans around this, but we will look into making this less heavy weight.

Are you using materialDirectives or did you include each component you are using individually? If it is the former you are paying the price of every message for every component. They are in a map so they aren't treeshaken.

cc @alan-knight

**Comment by alan-knight** [comment]
Messages are (or at least can be) deferred loaded, so the actual message text doesn't need to be a cost. There's the overhead of the mechanisms themselves for messages. And date and number formatting are in intl.dart as well and the number data is included. But if it's not using those at all then those should be able to be tree-shaken. But we could certainly investigate making sure that can happen.

**Comment by matanlurey** [comment]
Moved this over to https://github.com/dart-lang/i18n/issues/268
