### ISSUE TITLE
[Q] Any plans to provide layout components ?

### ISSUE THREAD

**Issue by sureshg** [dart-lang/angular2_components#39]
Layout components are super helpful and are the building block of your app layout. Many material design component libraries provide these layout components out of the box. 

Eg: Material Design Lite  (https://getmdl.io/components/index.html#layout-section) 

Does it make sense to provide these as dart angular2 components?

**Comment by nshahan** [comment]
Our immediate goal is to release the sass versions of our styles and those provide the flexbox layouts that we use. Not a standalone component.

**Comment by matanlurey** [comment]
Closing since we have https://github.com/dart-lang/angular2_components/issues/45

**Comment by adaojunior** [comment]
You can also take a look at [angular/flex-layout](https://github.com/angular/flex-layout) , it is interesting and I want to find some time to port it to dart and I could use some help :D

**Comment by pratikpparikh** [comment]
@adaojunior did you ever start on angular/flex-layout?

**Comment by adaojunior** [comment]
@pratikpparikh I didn't, would you be interested in contributing on that ?

**Comment by praveeno** [comment]
what is status guys, 
do we have something like angular/flex-layout in angular dart,
if anyone working on this, let me know i can also contribute
