### ISSUE TITLE
Radio buttons are distorted on IE11, see pictures attached

### ISSUE THREAD

**Issue by DanielTal** [dart-lang/angular2_components#40]
both photos taken from the live example, first one is on IE11, second is Opera

![e1](https://cloud.githubusercontent.com/assets/11020753/21316687/93173440-c60a-11e6-8aaa-34fe47cebed2.png)

**Comment by nshahan** [comment]
While many of the components do work in IE 11, compatibility is not guaranteed. Currently our support is for the last two versions of Chrome, Edge, Firefox, and Safari.

**Comment by stephan-gruen** [comment]
Bummer! It would be so easy to fix. Just change flex for then content div from flex:1 to flex:auto (so that flex-basis:0px changes to flex-basis:auto).

**Comment by nshahan** [comment]
@stephan-gruen Your recommended fix landed in #57. Thanks!
