### ISSUE TITLE
Popup position incorrect

### ISSUE THREAD

**Issue by red010b37** [dart-lang/angular2_components#47]
When using a flex layout the popup appears off screen/behind the screen making a x-scrollbar appear in the process. You can see scrollbar appear on the body in the screen shots. 

Also there is currently no way that I can see to force the top right alignment. This type of option would also alleviate this issue.

![screenshot from 2017-01-09 18-07-03](https://cloud.githubusercontent.com/assets/4919660/21757643/bb4561ac-d696-11e6-8c25-20fbd1b4e834.png)

![screenshot from 2017-01-09 18-07-15](https://cloud.githubusercontent.com/assets/4919660/21757642/bb44a78a-d696-11e6-9e93-0cd657f39df9.png)

**Comment by zoechi** [comment]
Please provide the HTML how you add it to the component.
It worked fine for me https://github.com/dart-lang/angular2_components/issues/42
The component has several options https://github.com/dart-lang/angular2_components/blob/35a783b204f4054636da2fe59f64f199902462de/lib/src/components/material_popup/material_popup.dart#L83 (but they are not fully documented yet)

**Comment by nshahan** [comment]
Closing issue due to lack of a response. Feel free to reopen if needed.
