### ISSUE TITLE
Glyph breakage due to disconnect.me strict protection mode in Firefox

### ISSUE THREAD

**Issue by Brahmasmi** [dart-lang/angular2_components#5]
This is an edge case and I am not sure where to log it.

The sample page (https://dart-lang.github.io/angular2_components_example/) has glyphs fetched from font.googleapis.com. These glyphs are not displayed when the disconnect.me strict protection mode is enabled in Firefox.

OS - Ubuntu 16.04.1
Browser - Firefox 49.0
Steps to reproduce -
1) Menu -> Preferences -> Privacy -> Change Block List.
2) Select the Disconnect.me strict protection option.
3) Navigate to https://dart-lang.github.io/angular2_components_example/.
Expected - Glyphs are shown
Actual - Placeholder text is shown instead of glyphs. Additionally, a shield icon is shown on the address bar next to the green lock.

**Comment by kevmoo** [comment]
We need more info. We're doing fonts + gh-pages in very typical ways.

**Comment by Brahmasmi** [comment]
Following URL does not show any shield in the address bar with the aforementioned FF settings:
https://azure.github.io
which implies that FF tracking protection blocks seem to be independent of gh-pages.

Following non gh-page (but accessing fonts.googleapis.com) displays absolutely nothing:
https://www.google.com/trends

Finally, "firefox --safe-mode" does show the glyphs on the angular2 components example page and does display the Google Trends page.

**Comment by matanlurey** [comment]
Honestly if Google trends isn't loading, I'd chock up FF having a bug.

**Comment by Brahmasmi** [comment]
As a temporary workaround - in the repro step 2, selecting basic protection instead of strict protection results in successful loading of the components example page and the Google Trends page. Perhaps we may want to explicitly document that glyphs may not work with strict tracking protection on FF.

I don't know whether this is a bug in FF tracking protection or in loading glyphs from fonts.googleapis.com (Google Trends seems to be running Angular 1). In a nutshell, only the aforementioned specific settings in the repro steps trigger this. It is an edge case, but nevertheless a valid end user configuration on the latest stock FF.

Frankly, I fail to comprehend why stock FF has this tracking protection block list - it explicitly states that "Some sites may not function properly" if the end user selects the strict option.

**Comment by nshahan** [comment]
I just looked on FireFox 49.0.2 and the Disconnect.me basic protection option was the default. I switched to strict protection, restarted and didn't see any problems with the Glyphs on https://dart-lang.github.io/angular2_components_example/. Are you still experiencing this issue?

**Comment by matanlurey** [comment]
I am closing this do to lack of response - please re-open if we can be of assistance.

**Comment by Brahmasmi** [comment]
Yup, works with newer FF versions with strict protection. Must be a bug with that specific FF version and we may have inadvertently encountered it. Thanks.
