### ISSUE TITLE
material-input of type number does not validate

### ISSUE THREAD

**Issue by sturmf** [dart-lang/angular2_components#50]
I try to let the user only input a number in a material-input and therefore set the type accordingly.
In the source of the material-input is stated: 

/// - `errorMsg` -- The error msg to be shown on the input if the max characters
///   are hit or the msg for an invalid number in the case of type = "number"

But no error is shown on invalid user input?

**Comment by TedSander** [comment]
Thanks for pointing this out. The documentation is actually wrong as that is how it worked with a previous version of this input, but the comment wasn't changed.

We currently don't have the number input open sourced, but you should see it land in the next update we land, which should be shortly.

cc: @nshahan

**Comment by nshahan** [comment]
Cleanup and new number input files landed in #57.
