### ISSUE TITLE
Setting button as disabled does not prevent triggering a click event

### ISSUE THREAD

**Issue by kostaa** [dart-lang/angular2_components#52]
When a button is disabled and the user moves the mouse over it the cursor changes to 'disabled' but if the user desides to click the button anyway a click event is generated.

To reproduce the issue: 
```
<material-button (click)="clicked()" disabled>Disabled</material-button>
	
void clicked() {
    print('clickety-click !!');
}


```

**Comment by matanlurey** [comment]
Material button's supported event is (trigger) not the native (click).

**Comment by kostaa** [comment]
Thanks for explanation that works for me now.
