### ISSUE TITLE
Material icons

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular2_components#53]
Material icons needs to import an external css inside the html. My question is if there is any way to include inside the css selector inside the component like this: 
`styleUrls: const ['app_component.css','https://fonts.googleapis.com/icon?family=Material+Icons'],`

**Comment by TedSander** [comment]
cc @matanlurey 

Not that I know of. Angular CSS is shimmed and compiled into the component itself. This would create many copies of that CSS resulting in a good amount of bloat. I also don't think the compiler would work on a URL currently.

**Comment by nshahan** [comment]
Ted is right. There isn't currently a way to do what you are asking for. The font icons need to be imported in the html.
