### ISSUE TITLE
Help with material-tooltip-text

### ISSUE THREAD

**Issue by nshahan** [dart-lang/angular2_components#59]
Original question by @dejan-marlovic

> hi, can you please help me? I know that this is not the right place to ask for help about this but I could not find solution to this anywhere else
>
> im trying to use:
<span tooltipTarget #ref="tooltipTarget">
Explicitly declare a tooltip component
>
> <material-tooltip-text [for]="ref">
Allows for   **formatted**   _text_.
>
>and I get an error:
Transform TemplateCompiler on tooltip|lib/app_component.ng_meta.json threw error: Template parse errors:
line 4, column 21 of AppComponent: ParseErrorLevel.FATAL: There is no directive with "exportAs" set to "tooltipTarget"
#ref="tooltipTarget"
>
> I can use other components fine

**Comment by TedSander** [comment]
MaterialTooltipTargetDirective needs to be in your directives list. It is the directive that provides tooltipTarget.

**Comment by dejan-marlovic** [comment]
hi thank you for your awswer!

how do I do that because this does not work :)

@Component(
  selector: 'my-app',
  styleUrls: const ['app_component.css'],
  templateUrl: 'app_component.html',
  directives: const [materialDirectives, MaterialTooltipTargetDirectives],
  providers: const [materialProviders],
)

**Comment by nshahan** [comment]
The directive is spelled without an "s" at the end: `MaterialTooltipTargetDirective`. It is already included in the convenience list `materialDirectives` here: 
https://github.com/dart-lang/angular2_components/blob/master/lib/angular2_components.dart#L53 

So you should already be getting the directive.

**Comment by TedSander** [comment]
Are there any other errors in the console log? or the build log?

It looks like materialProviders isn't enough on the providers side. Would also need: materialTooltipBindings

**Comment by dejan-marlovic** [comment]
does it help if I send this?

D:\Program\Dart\dart-sdk\bin\pub.bat serve web --port=62213
Loading source assets...
Loading angular2 and dart_to_js_script_rewriter transformers...
Serving tooltip web on http://localhost:62213
[web] GET index.html => tooltip|web/index.html
Build error:
Transform TemplateCompiler on tooltip|lib/app_component.ng_meta.json threw error: Template parse errors:
line 4, column 21 of AppComponent: ParseErrorLevel.FATAL: There is no directive with "exportAs" set to "tooltipTarget"
#ref="tooltipTarget"
^^^^^^^^^^^^^^^^^^^^
package:angular2/src/compiler/template_parser.dart 112                          TemplateParser.parse
package:angular2/src/compiler/offline_compiler.dart 111                         OfflineCompiler._compileComponent
package:angular2/src/compiler/offline_compiler.dart 67                          OfflineCompiler.compile.<fn>
dart:core-patch/array.dart 77                                                   List.forEach
package:angular2/src/compiler/offline_compiler.dart 64                          OfflineCompiler.compile
package:angular2/src/transform/template_compiler/generator.dart 53              processTemplates.<async>.<fn>
package:angular2/src/transform/common/logging.dart 37                           logElapsedSync
package:angular2/src/transform/template_compiler/generator.dart 52              processTemplates.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 467                                                 _Future._complete
dart:async/future_impl.dart 52                                                  _SyncCompleter.complete
package:angular2/src/transform/common/logging.dart 27                           logElapsedAsync.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 467                                                 _Future._complete
dart:async/future_impl.dart 52                                                  _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 116  _CompileDataCreator.createCompileData.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 467                                                 _Future._complete
dart:async/future_impl.dart 52                                                  _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 262  _CompileDataCreator._extractNgMeta.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 477                                                 _Future._completeWithValue
dart:async/future_impl.dart 528                                                 _Future._asyncComplete.<fn>
dart:async/zone.dart 1150                                                       _rootRun
dart:async/zone.dart 1026                                                       _CustomZone.run
dart:async/zone.dart 953                                                        _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                                           _microtaskLoop
dart:async/schedule_microtask.dart 50                                           _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                                        _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                                       _RawReceivePortImpl._handleMessage

package:angular2/src/compiler/template_parser.dart 112                          TemplateParser.parse
package:angular2/src/compiler/offline_compiler.dart 111                         OfflineCompiler._compileComponent
package:angular2/src/compiler/offline_compiler.dart 67                          OfflineCompiler.compile.<fn>
dart:core                                                                       List.forEach
package:angular2/src/compiler/offline_compiler.dart 64                          OfflineCompiler.compile
package:angular2/src/transform/template_compiler/generator.dart 53              processTemplates.<async>.<fn>
package:angular2/src/transform/common/logging.dart 37                           logElapsedSync
package:angular2/src/transform/template_compiler/generator.dart 52              processTemplates.<async>
dart:async                                                                      _SyncCompleter.complete
package:angular2/src/transform/common/logging.dart 27                           logElapsedAsync.<async>
dart:async                                                                      _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 116  _CompileDataCreator.createCompileData.<async>
dart:async                                                                      _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 262  _CompileDataCreator._extractNgMeta.<async>
Build completed with 1 errors.
[web] GET Served 6 assets.
[web] GET packages/tooltip/app_component.template.dart => Could not find asset tooltip|lib/app_component.template.dart.
[web] GET Served 8 assets.
[web] GET styles.css => (cached) tooltip|web/styles.css

**Comment by nshahan** [comment]
Interesting that it still works for the example application without that provider.

It if is necessary I will add `materialTooltipBindings` to `materialProviders` in my next push.

**Comment by dejan-marlovic** [comment]
cant add materialTooltipBindings inside providers list  it says: Argument of a constant creation must be constant expressions

**Comment by dejan-marlovic** [comment]
this is my yaml file if that helps:

name: angular2_components_example
description: An example app using the angular_components package.
version: 1.2.0
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2:
  angular2_components: ^0.3.1-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter

**Comment by TedSander** [comment]
Ahh it doesn't need that provider as it is using the pattern of defining it on the use of it itself.

What does your template look like? Can you get the example to work?

**Comment by nshahan** [comment]
I just wrote a quick test and it worked for me: 

**app_component.html**
```
<h1>Tooltip Test</h1>

<span tooltipTarget #ref="tooltipTarget">
  Explicitly declare a tooltip component<br/>
</span>

<material-tooltip-text [for]="ref">
    Allows for &nbsp; <strong>formatted</strong> &nbsp; <em>text</em>.
</material-tooltip-text>
```

**app_component.dart**
```
import 'package:angular2/core.dart';
import 'package:angular2_components/angular2_components.dart';

@Component(
  selector: 'my-app',
  styleUrls: const ['app_component.css'],
  templateUrl: 'app_component.html',
  directives: const [materialDirectives],
  providers: const [materialProviders],
)
class AppComponent {
  // Nothing here.
}
```

**Comment by dejan-marlovic** [comment]
i have just copied your files .. does not seem to work

**Comment by nshahan** [comment]
Do you get the same error? Can you run `pub deps` and paste the results?

**Comment by dejan-marlovic** [comment]
you mean this?
not sure how to run pub deps in phpstorm :)

D:\Program\Dart\dart-sdk\bin\pub.bat serve web --port=63198
Loading source assets...
Loading angular2 and dart_to_js_script_rewriter transformers...
Serving tooltip web on http://localhost:63198
[web] GET index.html => tooltip|web/index.html
[web] GET packages/browser/dart.js => browser|lib/dart.js
[web] GET styles.css => tooltip|web/styles.css
[web] GET Served 27 assets.
[web] GET Served 30 assets.
Build error:
Transform TemplateCompiler on tooltip|lib/app_component.ng_meta.json threw error: Template parse errors:
line 3, column 21 of AppComponent: ParseErrorLevel.FATAL: There is no directive with "exportAs" set to "tooltipTarget"
#ref="tooltipTarget"
^^^^^^^^^^^^^^^^^^^^
package:angular2/src/compiler/template_parser.dart 112                          TemplateParser.parse
package:angular2/src/compiler/offline_compiler.dart 111                         OfflineCompiler._compileComponent
package:angular2/src/compiler/offline_compiler.dart 67                          OfflineCompiler.compile.<fn>
dart:core-patch/array.dart 77                                                   List.forEach
package:angular2/src/compiler/offline_compiler.dart 64                          OfflineCompiler.compile
package:angular2/src/transform/template_compiler/generator.dart 53              processTemplates.<async>.<fn>
package:angular2/src/transform/common/logging.dart 37                           logElapsedSync
package:angular2/src/transform/template_compiler/generator.dart 52              processTemplates.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 467                                                 _Future._complete
dart:async/future_impl.dart 52                                                  _SyncCompleter.complete
package:angular2/src/transform/common/logging.dart 27                           logElapsedAsync.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 467                                                 _Future._complete
dart:async/future_impl.dart 52                                                  _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 116  _CompileDataCreator.createCompileData.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 467                                                 _Future._complete
dart:async/future_impl.dart 52                                                  _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 262  _CompileDataCreator._extractNgMeta.<async>
dart:async-patch/async_patch.dart 27                                            _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1158                                                       _rootRunUnary
dart:async/zone.dart 1037                                                       _CustomZone.runUnary
dart:async/future_impl.dart 131                                                 _FutureListener.handleValue
dart:async/future_impl.dart 637                                                 _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                                                 _Future._propagateToListeners
dart:async/future_impl.dart 477                                                 _Future._completeWithValue
dart:async/future_impl.dart 528                                                 _Future._asyncComplete.<fn>
dart:async/zone.dart 1150                                                       _rootRun
dart:async/zone.dart 1026                                                       _CustomZone.run
dart:async/zone.dart 953                                                        _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                                           _microtaskLoop
dart:async/schedule_microtask.dart 50                                           _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                                        _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                                       _RawReceivePortImpl._handleMessage

package:angular2/src/compiler/template_parser.dart 112                          TemplateParser.parse
package:angular2/src/compiler/offline_compiler.dart 111                         OfflineCompiler._compileComponent
package:angular2/src/compiler/offline_compiler.dart 67                          OfflineCompiler.compile.<fn>
dart:core                                                                       List.forEach
package:angular2/src/compiler/offline_compiler.dart 64                          OfflineCompiler.compile
package:angular2/src/transform/template_compiler/generator.dart 53              processTemplates.<async>.<fn>
package:angular2/src/transform/common/logging.dart 37                           logElapsedSync
package:angular2/src/transform/template_compiler/generator.dart 52              processTemplates.<async>
dart:async                                                                      _SyncCompleter.complete
package:angular2/src/transform/common/logging.dart 27                           logElapsedAsync.<async>
dart:async                                                                      _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 116  _CompileDataCreator.createCompileData.<async>
dart:async                                                                      _SyncCompleter.complete
package:angular2/src/transform/template_compiler/compile_data_creator.dart 262  _CompileDataCreator._extractNgMeta.<async>
[web] GET packages/tooltip/app_component.template.dart => Could not find asset tooltip|lib/app_component.template.dart.
Build completed with 1 errors.
[web] GET Served 138 assets.

**Comment by dejan-marlovic** [comment]
sorry this is my yaml file if it matters

name: tooltip
description: A web app that uses AngularDart Components
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

**Comment by nshahan** [comment]
OK I think this might be it. Can you try changing your dependencies to
```
  angular2: any
  angular2_components: 0.3.1-alpha
```
I think the restrictions you have are preventing pub from resolving a version of angular2_components that contains the Material Tooltip.

You are probably getting angular2_components version 0.2.2.

**Comment by dejan-marlovic** [comment]
thank you! that did it!!

**Comment by nshahan** [comment]
I'm glad that worked, but I will still make a note to add the provider we discussed in order to support more complicated patterns.

**Comment by TedSander** [comment]
I don't think you need to add the provider. Like I said it turns out that component uses a different style for injection so it isn't needed.
