### ISSUE TITLE
Color implements equals operator but not hashCode

### ISSUE THREAD

**Issue by ilikerobots** [dart-lang/angular2_components#7]
The Color class implements equals operator (==) but not hashCode

**Comment by sethladd** [comment]
I think there's an analyzer hint lint for this case?

**Comment by kevmoo** [comment]
> I think there's an analyzer hint lint for this case?

Yup, @sethladd

**Comment by kevmoo** [comment]
This has been fixed internally and will be merged over with the next sync. Assigning it to myself for tracking.

**Comment by nshahan** [comment]
Fixed in a16b3ddbe260ed9ea0d3bb3103d890a4e9b5cdc5
