### ISSUE TITLE
Changing theme

### ISSUE THREAD

**Issue by jrote1** [dart-lang/angular2_components#9]
Is it currently possible to change what colors are using for the material elements?

**Comment by thebitguru** [comment]
Check out [this html](https://github.com/dart-lang/angular2_components_example/blob/master/lib/app_component.html#L16) and [css](https://github.com/dart-lang/angular2_components_example/blob/master/lib/app_component.css).  Is that what you are looking for?

**Comment by jrote1** [comment]
@thebitguru Should be I'll check if it works on inputs etc then it will do what I am after, but would be could to be able to apply a theme to all elements unless overriden

**Comment by matanlurey** [comment]
We don't have theme customization published as the initial developer preview.

As @thebitguru outlined, it's loosely possible today, but not friendly. We'll have a formal SASS-based theming solution in a future release.

**Comment by thebitguru** [comment]
@matanlurey, what's the right channel to ask questions about the timeline for this project?  I am getting started on a new project and really Angular Dart so far, but I am worried that these components won't be ready for my project in time.

**Comment by matanlurey** [comment]
We don't publish timelines, as we are entirely a feature based, not time-based release.

If I had to guess, we will make good progress this quarter, but again, not a guarantee.

**Comment by jrote1** [comment]
@matanlurey ok thanks was just interested if it was available, are external contributions accepted at the moment?

**Comment by nshahan** [comment]
@jrote1 We are not setup to take external contributions currently but we are working towards that goal.
